import React from "react";
import { AbsoluteFill, useCurrentFrame, useVideoConfig, interpolate, spring } from "remotion";

export const Outro: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();

  const fadeIn = interpolate(frame, [0, 15], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const fadeOut = interpolate(frame, [durationInFrames - 30, durationInFrames], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  const checkSpring = spring({ frame: frame - 10, fps, config: { stiffness: 120, damping: 14 } });
  const checkScale = interpolate(checkSpring, [0, 1], [0.5, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  const textSpring = spring({ frame: frame - 25, fps, config: { stiffness: 80, damping: 18 } });

  return (
    <AbsoluteFill style={{ opacity: fadeIn * fadeOut, backgroundColor: "#0A0A0A", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
      <div style={{ width: 80, height: 80, borderRadius: "50%", border: "3px solid #4CAF50", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 32, transform: `scale(${checkScale})`, opacity: checkSpring }}>
        <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#4CAF50" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          <path d="M5 13l4 4L19 7" />
        </svg>
      </div>
      <h2 style={{ fontFamily: "sans-serif", fontSize: 42, fontWeight: 600, color: "#FAFAFA", margin: 0, opacity: textSpring, transform: `translateY(${interpolate(textSpring, [0, 1], [15, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })}px)` }}>
        操作完了
      </h2>
      <p style={{ fontFamily: "monospace", fontSize: 14, color: "rgba(255,255,255,0.3)", marginTop: 12, opacity: interpolate(textSpring, [0.5, 1], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }) }}>
        Generated by Video Edit Agent
      </p>
    </AbsoluteFill>
  );
};
